"""Add FK from regime_snapshots.symbol to stocks.symbol.

Revision ID: 10c2e77aef47
Revises: 4641962d2bd8
Create Date: 2026-04-21 05:08:14.911662
"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "10c2e77aef47"
down_revision: Union[str, Sequence[str], None] = "4641962d2bd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "regime_snapshots", "stocks", ["symbol"], ["symbol"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "regime_snapshots", type_="foreignkey")
    # ### end Alembic commands ###
