"""add is_system and sort_order to watchlist_categories

Revision ID: 1d7173749a9a
Revises: 4ca0d9c9f632
Create Date: 2026-04-12 04:56:51.551436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d7173749a9a"
down_revision: Union[str, Sequence[str], None] = "4ca0d9c9f632"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watchlist_categories",
        sa.Column("is_system", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "watchlist_categories",
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("watchlist_categories", "sort_order")
    op.drop_column("watchlist_categories", "is_system")
    # ### end Alembic commands ###
