"""Change options_agent date columns from DateTime to Date type.

Revision ID: 16f51c6541c6
Revises: 10c2e77aef47
Create Date: 2026-04-21 06:00:00.000000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16f51c6541c6"
down_revision: Union[str, Sequence[str], None] = "10c2e77aef47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Change IVRSnapshot.as_of_date from DateTime to Date
    op.execute(
        'ALTER TABLE ivr_snapshots ALTER COLUMN "as_of_date" TYPE DATE USING "as_of_date"::date'
    )

    # Change OptionsEodChain.as_of_date and expiry_date from DateTime to Date
    op.execute(
        'ALTER TABLE options_eod_chains ALTER COLUMN "as_of_date" TYPE DATE USING "as_of_date"::date'
    )
    op.execute(
        'ALTER TABLE options_eod_chains ALTER COLUMN "expiry_date" TYPE DATE USING "expiry_date"::date'
    )

    # Change RegimeSnapshot.as_of_date from DateTime to Date
    op.execute(
        'ALTER TABLE regime_snapshots ALTER COLUMN "as_of_date" TYPE DATE USING "as_of_date"::date'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert IVRSnapshot.as_of_date from Date to DateTime
    op.execute(
        'ALTER TABLE ivr_snapshots ALTER COLUMN "as_of_date" TYPE TIMESTAMP USING "as_of_date"::timestamp'
    )

    # Revert OptionsEodChain.as_of_date and expiry_date from Date to DateTime
    op.execute(
        'ALTER TABLE options_eod_chains ALTER COLUMN "as_of_date" TYPE TIMESTAMP USING "as_of_date"::timestamp'
    )
    op.execute(
        'ALTER TABLE options_eod_chains ALTER COLUMN "expiry_date" TYPE TIMESTAMP USING "expiry_date"::timestamp'
    )

    # Revert RegimeSnapshot.as_of_date from Date to DateTime
    op.execute(
        'ALTER TABLE regime_snapshots ALTER COLUMN "as_of_date" TYPE TIMESTAMP USING "as_of_date"::timestamp'
    )
    # ### end Alembic commands ###
