"""Add options_eod_chains table.

Revision ID: 94c6a69eb80e
Revises: 6516f179a9f2
Create Date: 2026-04-20 14:55:55.862495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "94c6a69eb80e"
down_revision: Union[str, Sequence[str], None] = "6516f179a9f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "options_eod_chains",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("as_of_date", sa.DateTime(), nullable=False),
        sa.Column("expiry_date", sa.DateTime(), nullable=False),
        sa.Column("expiry_bucket", sa.String(length=16), nullable=False),
        sa.Column("contract_type", sa.String(length=1), nullable=False),
        sa.Column("strike", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("bid", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("ask", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("mid", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("last", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("open_interest", sa.Integer(), nullable=True),
        sa.Column("iv", sa.NUMERIC(precision=8, scale=4), nullable=True),
        sa.Column("delta", sa.NUMERIC(precision=8, scale=4), nullable=True),
        sa.Column("gamma", sa.NUMERIC(precision=10, scale=6), nullable=True),
        sa.Column("theta", sa.NUMERIC(precision=10, scale=6), nullable=True),
        sa.Column("vega", sa.NUMERIC(precision=10, scale=6), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["symbol"], ["stocks.symbol"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol",
            "as_of_date",
            "expiry_date",
            "contract_type",
            "strike",
            name="uq_chain_contract",
        ),
    )
    op.create_index(
        "ix_chain_expiry_bucket",
        "options_eod_chains",
        ["symbol", "as_of_date", "expiry_bucket"],
        unique=False,
    )
    op.create_index(
        "ix_chain_symbol_asof", "options_eod_chains", ["symbol", "as_of_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chain_symbol_asof", table_name="options_eod_chains")
    op.drop_index("ix_chain_expiry_bucket", table_name="options_eod_chains")
    op.drop_table("options_eod_chains")
    # ### end Alembic commands ###
