"""Add regime_snapshots table for market regime classification.

Revision ID: 4641962d2bd8
Revises: 94c6a69eb80e
Create Date: 2026-04-20 15:26:48.692703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4641962d2bd8"
down_revision: Union[str, Sequence[str], None] = "94c6a69eb80e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regime_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("as_of_date", sa.DateTime(), nullable=False),
        sa.Column("regime", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=True),
        sa.Column("adx", sa.NUMERIC(precision=6, scale=2), nullable=True),
        sa.Column("atr_pct", sa.NUMERIC(precision=6, scale=4), nullable=True),
        sa.Column("spy_trend_20d", sa.NUMERIC(precision=8, scale=6), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "as_of_date", name="uq_regime_symbol_date"),
    )
    op.create_index("ix_regime_symbol", "regime_snapshots", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_regime_symbol", table_name="regime_snapshots")
    op.drop_table("regime_snapshots")
    # ### end Alembic commands ###
