"""Add ivr_snapshots table.

Revision ID: 6516f179a9f2
Revises: 10401f8024b1
Create Date: 2026-04-20 09:23:37.922712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6516f179a9f2"
down_revision: Union[str, Sequence[str], None] = "10401f8024b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ivr_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("as_of_date", sa.DateTime(), nullable=False),
        sa.Column("ivr", sa.NUMERIC(precision=5, scale=2), nullable=False),
        sa.Column("current_hv", sa.NUMERIC(precision=8, scale=4), nullable=False),
        sa.Column("calculation_basis", sa.String(length=16), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stocks.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol", "as_of_date", "calculation_basis", name="uq_ivr_symbol_date_basis"
        ),
    )
    op.create_index("ix_ivr_as_of", "ivr_snapshots", ["as_of_date"], unique=False)
    op.create_index("ix_ivr_symbol", "ivr_snapshots", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ivr_symbol", table_name="ivr_snapshots")
    op.drop_index("ix_ivr_as_of", table_name="ivr_snapshots")
    op.drop_table("ivr_snapshots")
    # ### end Alembic commands ###
