"""Initial schema.

Revision ID: df27d5f1133c
Revises:
Create Date: 2026-04-05 06:35:47.106472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df27d5f1133c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_indicators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("indicator_name", sa.String(length=255), nullable=False),
        sa.Column("release_date", sa.DateTime(), nullable=False),
        sa.Column("value", sa.NUMERIC(precision=15, scale=4), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "indicator_name", "release_date", name="uq_economic_indicator_name_date"
        ),
    )
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stocks_symbol"), "stocks", ["symbol"], unique=True)
    op.create_table(
        "daily_candles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("open", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("high", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("low", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("close", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stock_id", "timestamp", name="uq_daily_candles_stock_ts"),
    )
    op.create_index(
        "ix_daily_candles_stock_ts", "daily_candles", ["stock_id", "timestamp"], unique=False
    )
    op.create_table(
        "earnings_calendar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_quarter", sa.Integer(), nullable=True),
        sa.Column("earnings_date", sa.DateTime(), nullable=False),
        sa.Column("report_date", sa.DateTime(), nullable=True),
        sa.Column("report_time", sa.String(length=50), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("reported_eps", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("estimated_eps", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stock_id", "earnings_date", name="uq_earnings_stock_date"),
    )
    op.create_index("ix_earnings_date", "earnings_calendar", ["earnings_date"], unique=False)
    op.create_table(
        "intraday_candles",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("resolution", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("open", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("high", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("low", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("close", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stock_id", "resolution", "timestamp", name="uq_intraday_candles_stock_res_ts"
        ),
    )
    op.create_index(
        "ix_intraday_candles_stock_ts", "intraday_candles", ["stock_id", "timestamp"], unique=False
    )
    op.create_table(
        "options_quotes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("option_symbol", sa.String(length=50), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("bid", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("ask", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("bid_size", sa.BigInteger(), nullable=True),
        sa.Column("ask_size", sa.BigInteger(), nullable=True),
        sa.Column("last", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("open_interest", sa.BigInteger(), nullable=True),
        sa.Column("delta", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("gamma", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("theta", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("vega", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("iv", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("underlying_price", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("option_symbol", "timestamp", name="uq_options_symbol_ts"),
    )
    op.create_index(
        "ix_options_stock_ts", "options_quotes", ["stock_id", "timestamp"], unique=False
    )
    op.create_table(
        "realtime_quotes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("bid", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("ask", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("bid_size", sa.BigInteger(), nullable=True),
        sa.Column("ask_size", sa.BigInteger(), nullable=True),
        sa.Column("last", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("open", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("high", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("low", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("close", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("change", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("change_pct", sa.NUMERIC(precision=10, scale=4), nullable=True),
        sa.Column("week_52_high", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("week_52_low", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_realtime_quotes_stock_ts", "realtime_quotes", ["stock_id", "timestamp"], unique=False
    )
    op.create_table(
        "scanner_results",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("scanner_name", sa.String(length=255), nullable=False),
        sa.Column("result_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("matched_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scanner_results_name_ts",
        "scanner_results",
        ["scanner_name", "matched_at"],
        unique=False,
    )
    op.create_index(
        "ix_scanner_results_stock_ts", "scanner_results", ["stock_id", "matched_at"], unique=False
    )
    op.create_table(
        "stock_news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("publication_date", sa.DateTime(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["stock_id"], ["stocks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stock_news_pubdate", "stock_news", ["publication_date"], unique=False)
    op.create_index(
        "ix_stock_news_stock_pubdate", "stock_news", ["stock_id", "publication_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_news_stock_pubdate", table_name="stock_news")
    op.drop_index("ix_stock_news_pubdate", table_name="stock_news")
    op.drop_table("stock_news")
    op.drop_index("ix_scanner_results_stock_ts", table_name="scanner_results")
    op.drop_index("ix_scanner_results_name_ts", table_name="scanner_results")
    op.drop_table("scanner_results")
    op.drop_index("ix_realtime_quotes_stock_ts", table_name="realtime_quotes")
    op.drop_table("realtime_quotes")
    op.drop_index("ix_options_stock_ts", table_name="options_quotes")
    op.drop_table("options_quotes")
    op.drop_index("ix_intraday_candles_stock_ts", table_name="intraday_candles")
    op.drop_table("intraday_candles")
    op.drop_index("ix_earnings_date", table_name="earnings_calendar")
    op.drop_table("earnings_calendar")
    op.drop_index("ix_daily_candles_stock_ts", table_name="daily_candles")
    op.drop_table("daily_candles")
    op.drop_index(op.f("ix_stocks_symbol"), table_name="stocks")
    op.drop_table("stocks")
    op.drop_table("economic_indicators")
    # ### end Alembic commands ###
