/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    /**
     * Health
     * @description Return service liveness status.
     */
    get: operations["health_api_health_get"];
  };
  "/api/auth/login": {
    /**
     * Login
     * @description Authenticate user with username and password, return session cookie.
     */
    post: operations["login_api_auth_login_post"];
  };
  "/api/auth/logout": {
    /**
     * Logout
     * @description Invalidate the session cookie and logout the user.
     */
    post: operations["logout_api_auth_logout_post"];
  };
  "/api/me": {
    /**
     * Me
     * @description Return the currently authenticated user.
     */
    get: operations["me_api_me_get"];
  };
  "/api/settings": {
    /**
     * Get Settings
     * @description Return all UI settings for the authenticated user.
     */
    get: operations["get_settings_api_settings_get"];
    /**
     * Put Settings
     * @description Upsert UI settings; return full settings (including defaults for unset keys).
     */
    put: operations["put_settings_api_settings_put"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * LoginRequest
     * @description Login request with username and password.
     */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /**
     * SettingsOut
     * @description Full settings response returned by GET and PUT /api/settings.
     */
    SettingsOut: {
      /** Theme */
      theme: string;
      /** Timezone */
      timezone: string;
    };
    /**
     * SettingsPatch
     * @description Keys that may be updated via PUT /api/settings.
     *
     * Add fields here when new sub-projects introduce settings.
     */
    SettingsPatch: {
      /** Theme */
      theme?: ("light" | "dark") | null;
      /** Timezone */
      timezone?: string | null;
    };
    /**
     * UserOut
     * @description User response model.
     */
    UserOut: {
      /** Id */
      id: number;
      /** Username */
      username: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

// Convenience type aliases — import these in application code instead of the raw components paths.
export type UserOut = components["schemas"]["UserOut"];
export type SettingsOut = components["schemas"]["SettingsOut"];
export type SettingsPatch = components["schemas"]["SettingsPatch"];
export type LoginRequest = components["schemas"]["LoginRequest"];

export interface operations {

  /**
   * Health
   * @description Return service liveness status.
   */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Login
   * @description Authenticate user with username and password, return session cookie.
   */
  login_api_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Logout
   * @description Invalidate the session cookie and logout the user.
   */
  logout_api_auth_logout_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Me
   * @description Return the currently authenticated user.
   */
  me_api_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  /**
   * Get Settings
   * @description Return all UI settings for the authenticated user.
   */
  get_settings_api_settings_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsOut"];
        };
      };
    };
  };
  /**
   * Put Settings
   * @description Upsert UI settings; return full settings (including defaults for unset keys).
   */
  put_settings_api_settings_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
